# flightstatus.xml

Header header
string Armed
string FlightMode

string DISARMED = "Disarmed"
string ARMING = "Arming"
string ARMED = "Armed"

string MANUAL = "Manual"
string SATABILIZED1 = "Stabilized1"
string SATABILIZED2 = "Stabilized2"
string SATABILIZED3 = "Stabilized3"
string AUTOTUNE = "Autotune"
string ALTITUDEHOLD = "AltitudeHold"
string ALTITUDEVARIO = "AltitudeVario"
string VELOCITYCONTROL = "VelocityControl"
string POSITIONHOLD = "PositionHold"
string RETURNTOBASE = "ReturnToBase"
string LAND = "Land"
string PATHPLANNER = "PathPlanner"
string POI = "POI"
